# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import node_report_pb2 as node__report__pb2
from . import aquaticus_vehicle_pb2 as aquaticus__vehicle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent_state.proto',
  package='mivp_agent',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61gent_state.proto\x12\nmivp_agent\x1a\x11node_report.proto\x1a\x17\x61quaticus_vehicle.proto\"}\n\nAgentState\x12\x11\n\tMOOS_TIME\x18\x01 \x02(\x02\x12-\n\x07vehicle\x18\x02 \x02(\x0b\x32\x1c.mivp_agent.AquaticusVehicle\x12-\n\rother_reports\x18\x03 \x03(\x0b\x32\x16.mivp_agent.NodeReport'
  ,
  dependencies=[node__report__pb2.DESCRIPTOR,aquaticus__vehicle__pb2.DESCRIPTOR,])




_AGENTSTATE = _descriptor.Descriptor(
  name='AgentState',
  full_name='mivp_agent.AgentState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='MOOS_TIME', full_name='mivp_agent.AgentState.MOOS_TIME', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='mivp_agent.AgentState.vehicle', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other_reports', full_name='mivp_agent.AgentState.other_reports', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=202,
)

_AGENTSTATE.fields_by_name['vehicle'].message_type = aquaticus__vehicle__pb2._AQUATICUSVEHICLE
_AGENTSTATE.fields_by_name['other_reports'].message_type = node__report__pb2._NODEREPORT
DESCRIPTOR.message_types_by_name['AgentState'] = _AGENTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentState = _reflection.GeneratedProtocolMessageType('AgentState', (_message.Message,), {
  'DESCRIPTOR' : _AGENTSTATE,
  '__module__' : 'agent_state_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.AgentState)
  })
_sym_db.RegisterMessage(AgentState)


# @@protoc_insertion_point(module_scope)
