# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mivp_agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import moos_pb2 as moos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mivp_agent.proto',
  package='mivp_agent',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10mivp_agent.proto\x12\nmivp_agent\x1a\nmoos.proto\"S\n\rEpisodeReport\x12\x0b\n\x03NUM\x18\x01 \x02(\x05\x12\x0f\n\x07SUCCESS\x18\x02 \x02(\x08\x12\x10\n\x08\x44URATION\x18\x03 \x02(\x01\x12\x12\n\nWILL_PAUSE\x18\x04 \x02(\x08\"\xb2\x01\n\x05State\x12%\n\x05vinfo\x18\x01 \x02(\x0b\x32\x16.mivp_agent.NodeReport\x12!\n\x04vars\x18\x02 \x03(\x0b\x32\x13.mivp_agent.MOOSVar\x12,\n\x0cnode_reports\x18\x03 \x03(\x0b\x32\x16.mivp_agent.NodeReport\x12\x31\n\x0e\x65pisode_report\x18\x04 \x01(\x0b\x32\x19.mivp_agent.EpisodeReport\"]\n\x06\x41\x63tion\x12\x0e\n\x06\x63ourse\x18\x01 \x02(\x01\x12\r\n\x05speed\x18\x02 \x02(\x01\x12\"\n\x05posts\x18\x03 \x03(\x0b\x32\x13.mivp_agent.MOOSVar\x12\x10\n\x08\x63trl_msg\x18\x04 \x02(\t\"i\n\nTransition\x12\x1d\n\x02s1\x18\x01 \x02(\x0b\x32\x11.mivp_agent.State\x12\x1d\n\x01\x61\x18\x02 \x02(\x0b\x32\x12.mivp_agent.Action\x12\x1d\n\x02s2\x18\x03 \x02(\x0b\x32\x11.mivp_agent.State'
  ,
  dependencies=[moos__pb2.DESCRIPTOR,])




_EPISODEREPORT = _descriptor.Descriptor(
  name='EpisodeReport',
  full_name='mivp_agent.EpisodeReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='NUM', full_name='mivp_agent.EpisodeReport.NUM', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SUCCESS', full_name='mivp_agent.EpisodeReport.SUCCESS', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='DURATION', full_name='mivp_agent.EpisodeReport.DURATION', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='WILL_PAUSE', full_name='mivp_agent.EpisodeReport.WILL_PAUSE', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=127,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='mivp_agent.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vinfo', full_name='mivp_agent.State.vinfo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vars', full_name='mivp_agent.State.vars', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_reports', full_name='mivp_agent.State.node_reports', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episode_report', full_name='mivp_agent.State.episode_report', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=308,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='mivp_agent.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='course', full_name='mivp_agent.Action.course', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='mivp_agent.Action.speed', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posts', full_name='mivp_agent.Action.posts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctrl_msg', full_name='mivp_agent.Action.ctrl_msg', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=403,
)


_TRANSITION = _descriptor.Descriptor(
  name='Transition',
  full_name='mivp_agent.Transition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s1', full_name='mivp_agent.Transition.s1', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='a', full_name='mivp_agent.Transition.a', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s2', full_name='mivp_agent.Transition.s2', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=510,
)

_STATE.fields_by_name['vinfo'].message_type = moos__pb2._NODEREPORT
_STATE.fields_by_name['vars'].message_type = moos__pb2._MOOSVAR
_STATE.fields_by_name['node_reports'].message_type = moos__pb2._NODEREPORT
_STATE.fields_by_name['episode_report'].message_type = _EPISODEREPORT
_ACTION.fields_by_name['posts'].message_type = moos__pb2._MOOSVAR
_TRANSITION.fields_by_name['s1'].message_type = _STATE
_TRANSITION.fields_by_name['a'].message_type = _ACTION
_TRANSITION.fields_by_name['s2'].message_type = _STATE
DESCRIPTOR.message_types_by_name['EpisodeReport'] = _EPISODEREPORT
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Transition'] = _TRANSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EpisodeReport = _reflection.GeneratedProtocolMessageType('EpisodeReport', (_message.Message,), {
  'DESCRIPTOR' : _EPISODEREPORT,
  '__module__' : 'mivp_agent_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.EpisodeReport)
  })
_sym_db.RegisterMessage(EpisodeReport)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'mivp_agent_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.State)
  })
_sym_db.RegisterMessage(State)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'mivp_agent_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.Action)
  })
_sym_db.RegisterMessage(Action)

Transition = _reflection.GeneratedProtocolMessageType('Transition', (_message.Message,), {
  'DESCRIPTOR' : _TRANSITION,
  '__module__' : 'mivp_agent_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.Transition)
  })
_sym_db.RegisterMessage(Transition)


# @@protoc_insertion_point(module_scope)
