# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='node_report.proto',
  package='mivp_agent',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11node_report.proto\x12\nmivp_agent\"N\n\nNodeReport\x12\r\n\x05vname\x18\x01 \x02(\t\x12\r\n\x05NAV_X\x18\x02 \x02(\x02\x12\r\n\x05NAV_Y\x18\x03 \x02(\x02\x12\x13\n\x0bNAV_HEADING\x18\x04 \x02(\x02'
)




_NODEREPORT = _descriptor.Descriptor(
  name='NodeReport',
  full_name='mivp_agent.NodeReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vname', full_name='mivp_agent.NodeReport.vname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NAV_X', full_name='mivp_agent.NodeReport.NAV_X', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NAV_Y', full_name='mivp_agent.NodeReport.NAV_Y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NAV_HEADING', full_name='mivp_agent.NodeReport.NAV_HEADING', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['NodeReport'] = _NODEREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeReport = _reflection.GeneratedProtocolMessageType('NodeReport', (_message.Message,), {
  'DESCRIPTOR' : _NODEREPORT,
  '__module__' : 'node_report_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.NodeReport)
  })
_sym_db.RegisterMessage(NodeReport)


# @@protoc_insertion_point(module_scope)
