# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moos.proto',
  package='mivp_agent',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmoos.proto\x12\nmivp_agent\"M\n\x07MOOSVar\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x0e\n\x04sval\x18\x02 \x01(\tH\x00\x12\x0e\n\x04\x64val\x18\x03 \x01(\x01H\x00\x12\x0e\n\x04\x62val\x18\x04 \x01(\x08H\x00\x42\x05\n\x03val\"a\n\nNodeReport\x12\r\n\x05vname\x18\x01 \x02(\t\x12\r\n\x05NAV_X\x18\x02 \x02(\x01\x12\r\n\x05NAV_Y\x18\x03 \x02(\x01\x12\x13\n\x0bNAV_HEADING\x18\x04 \x02(\x01\x12\x11\n\tMOOS_TIME\x18\x05 \x02(\x01'
)




_MOOSVAR = _descriptor.Descriptor(
  name='MOOSVar',
  full_name='mivp_agent.MOOSVar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mivp_agent.MOOSVar.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sval', full_name='mivp_agent.MOOSVar.sval', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dval', full_name='mivp_agent.MOOSVar.dval', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bval', full_name='mivp_agent.MOOSVar.bval', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='val', full_name='mivp_agent.MOOSVar.val',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=26,
  serialized_end=103,
)


_NODEREPORT = _descriptor.Descriptor(
  name='NodeReport',
  full_name='mivp_agent.NodeReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vname', full_name='mivp_agent.NodeReport.vname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NAV_X', full_name='mivp_agent.NodeReport.NAV_X', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NAV_Y', full_name='mivp_agent.NodeReport.NAV_Y', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NAV_HEADING', full_name='mivp_agent.NodeReport.NAV_HEADING', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MOOS_TIME', full_name='mivp_agent.NodeReport.MOOS_TIME', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=202,
)

_MOOSVAR.oneofs_by_name['val'].fields.append(
  _MOOSVAR.fields_by_name['sval'])
_MOOSVAR.fields_by_name['sval'].containing_oneof = _MOOSVAR.oneofs_by_name['val']
_MOOSVAR.oneofs_by_name['val'].fields.append(
  _MOOSVAR.fields_by_name['dval'])
_MOOSVAR.fields_by_name['dval'].containing_oneof = _MOOSVAR.oneofs_by_name['val']
_MOOSVAR.oneofs_by_name['val'].fields.append(
  _MOOSVAR.fields_by_name['bval'])
_MOOSVAR.fields_by_name['bval'].containing_oneof = _MOOSVAR.oneofs_by_name['val']
DESCRIPTOR.message_types_by_name['MOOSVar'] = _MOOSVAR
DESCRIPTOR.message_types_by_name['NodeReport'] = _NODEREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MOOSVar = _reflection.GeneratedProtocolMessageType('MOOSVar', (_message.Message,), {
  'DESCRIPTOR' : _MOOSVAR,
  '__module__' : 'moos_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.MOOSVar)
  })
_sym_db.RegisterMessage(MOOSVar)

NodeReport = _reflection.GeneratedProtocolMessageType('NodeReport', (_message.Message,), {
  'DESCRIPTOR' : _NODEREPORT,
  '__module__' : 'moos_pb2'
  # @@protoc_insertion_point(class_scope:mivp_agent.NodeReport)
  })
_sym_db.RegisterMessage(NodeReport)


# @@protoc_insertion_point(module_scope)
