name: Docker Build

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Debug Info
      run: ls -la
    - name: Build docker container
      run: ./docker.sh build
    - name: Test docker container
      run: ./docker.sh test
