name: Python Build

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  DEBUG_OUTPUT: false

jobs:
  build-n-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install deps for ubuntu 18 runners
      if: matrix.os == 'ubuntu-18.04'
      run: pip3 install setuptools wheel
    - name: Install mivp_agent
      run: cd src/python_module && pip3 install .
    - name: Install mivp_agent testing deps
      run: cd src/python_module && pip3 install .[test]
    - name: Run python tests
      run: cd src/python_module/test && ./test_all.py
