name: Python Build

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  DEBUG_OUTPUT: false

jobs:
  build-n-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@
    - name: Install python versions for Linux
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt-get install -y python3.7 python3.8
    - name: Install python versions for MacOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install python@3.7 python@3.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install tox
      run: pip install tox
    - name: Run python tests
      run: cd src/python_module/test && tox
