name: Python Build

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  DEBUG_OUTPUT: false

jobs:
  build-n-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    # Note: actions/setup-python@v2 does not support deadsnakes
    - name: Install python versions for Linux
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt-get install python3.7 python3.7-distutils
        sudo apt-get install -y python3.8 python3.8-distutils
    - name: Install python versions for MacOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install pyenv
        pyenv install 3.7
        pyenv install 3.8
        pyenv global 3.7 3.8
        pyenv versions
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install tox
      run: pip install tox
    - name: Run python tests
      if: runner.os == 'Linux'
      run: |
        cd src/python_module/test
        tox
    - name: Run python tests
      if: runner.os == 'macOS'
      run: |
        pyenv local 3.7 3.8
        cd src/python_module/test
        tox
